CC=gcc
CFLAGS=-lpthread

all: ex1 t1 t2 t3

ex1: ex1.c
	$(CC) -o ex1 $(CFLAGS) ex1.c

t1: t1.c
	$(CC) -o t1 $(CFLAGS) t1.c

t2: t2.c
	$(CC) -o t2 $(CFLAGS) t2.c

t3: t3.c
	$(CC) -o t3 $(CFLAGS) t3.c

clean: 
	rm ex1 t1 t2 t3

